development:
  adapter: postgresql
  encoding: unicode
  database: ticket-shop_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ticket-shop_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ticket-shop_production
  pool: 5

